language: node_js
env:
  matrix:
    secure: vfVxjpb9OjvWBa+jk3asroSTD62kS/M8Y5YS68q2deWa6xAJlGEEFS4BEGjfCOA/kn0rHQXet59MjtsOiU3yRMxjTWWoBG/xQA37nS8izj+GD4DtprO5sMMcsmkwikU57qbK0a94oSGcqtL0VindKOWwhL4tbl2v8EfCLJdPQxseEelUZm4eX7RIqEEVdBscL81/UM2DK3/eCyRs32NjMP9QKz2a6X3KW4ziGnjywoY4ZqM0/Jjrk4V0RyLekh3TH9U6AinkrhJwEOAXaxqL245vv9uw0kuBG46VgopMKzc3VHjB2jWLeJZO8hVWAtzQIZw43sLsMrd3wYJAEPI9zpsYy22VdmF9pgqP1vzu3f1nb+wsK2XxICgJonsI6EBw0Wmt80DwLnzg8W/APfah9M0r/U2KhPJ/YOspHyUBi7Jmy8n+JruTt1Cl4+Qm58TNy5vYFkY915cabT+npOtop6jDyvljeHOxELgfFqwOTNqyRSEkj+Z3y7jQs18okHy4CSjXOw7bApRasNLXSPpTHN+kVlcuuMcWcZ/b1mxDsEsrSAVFgg1ueER2gqcNnUrwK1EOl3NLO3UTc4DzWN9gxgNdB700gIoxBMm695iAsvUfJI7M0B3yefY83Wi+cha2cRhD/qKDFfhtKo1cKBnldM5HRD5jgOi9ZEuZ/Z5/j+s=
cache:
  directories:
  - node_modules
script:
- npm run build-prod
deploy:
  provider: pages
  github-token: "$GH_TOKEN"
  on:
    branch: master
  local_dir: dist
  edge: true
