language: node_js
env:
  matrix:
    secure: BYLAovgLL4F9aDsjI+x9Kv2eQHaJx6Hg7Y0YrEjUKnnG668Jtlz01VNkcYk1ZFIhYK8M80/sFvUo4afJBKKnx0SsykqdGykeH+aas/viAWK6Nl+0MUJZgYYJ9LGueWiwy6M0vKuUWWQ8NRuAP9IZkAR6ehW36f/+PSgyukaWzaBgkYI5NLgTRBQcbj7XojIn52RDhj40ZgxulIelL8wejmbQ70WCs9LNiLIr2w0vcRm5xW7d5XM5Tl4KNvxavdaY0p58gpbZWbMbcpxwICwRE8EkzgeaYNU26m3+J3GhqW9zhqe+EYQhZ3K/qIioiwhiHl3ipyslZ/JAUu+Htkc+HGcmG3JQKHNb0qN6bca5VkkVTAD5kvdNR93H3TyvdlSfG57dwaO0CFceOadIatnHfkm1tNuUPhedExuUOk6dZ4PWCXx4X3J/WhTsbfs2onGKVr0Mj6XLZN+Cg81xaJ0vO7M8wrsYx0gI/auxAlA+d2qrK7O05xFDlAj3SYg0msmcETHTunIJVK8SNRyskj2sBlEPp7IQjZAbvQsm+NItNIQOZemmY5+Qvti/rnEbSvtKbTGciR3JXz8R57VU3wF/y90+LD3TwVaeWwSTZYiFUEOl5ddx3nAzOiK+X/2IXjHhLas5jB7xKpnfPqn5uawDoft07gYwjvPLDjgVR7rn1vU=
cache:
  directories:
  - node_modules
script:
- npm run build-prod
deploy:
  provider: pages
  github-token: "$GH_TOKEN"
  on:
    branch: master
  local_dir: dist
  edge: true
